name: Continuous Benchmarks
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  RSPM: "https://packagemanager.rstudio.com/cran/__linux__/bionic/291"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        with:
          fetch-depth: 0
        uses: actions/checkout@master
      - name: Set up git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: Ensure base branch is fetched
        if: ${{ github.event_name == 'pull_request' }}
        run: git branch $GITHUB_BASE_REF remotes/origin/$GITHUB_BASE_REF; git branch
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.0'
          http-user-agent: "R/4.0.0 (ubuntu-18.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions"
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          sudo apt-get install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('gert', 'ggplot2', 'purrr'))" -e "remotes::install_deps(dependencies = TRUE); remotes::install_github('r-lib/bench')"
          R CMD INSTALL .
      - name: Checkout benchmarking repo
        uses: actions/checkout@v2
        with:
          repository: lorenzwalthert/here
          ref: ca9c8e69c727def88d8ba1c8b85b0e0bcea87b3f
          path: bench/sources/here
      - name: Fetch existing benchmarks
        run: Rscript -e 'rlang::with_handlers(bench::cb_fetch(), error = function(e) paste("Could not fetch benchmarks, skipping. The error was", conditionMessage(e)))'
      - name: Run benchmarks
        run: Rscript -e 'bench::cb_run()'
      - name: Show benchmarks
        run: git notes --ref benchmarks show
      - uses: actions/upload-artifact@v2
        with:
          name: visual-benchmarks
          path: bench/plots/
      - name: Push benchmarks
        if: ${{ github.event_name == 'push' }}
        run: Rscript -e "bench::cb_push()"
